version: '3.7'

services:
  traefik:
    container_name: traefik
    image: traefik:v2.7
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.api.rule=Host(`traefik.dev.neuvy.eu`)"
      - "traefik.http.routers.api.service=api@internal"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  front:
    container_name: front
    build: 
      context: ./frontend
      dockerfile: Dockerfile-dev
    command: npm run dev
    expose:
      - 3000
      - 3333
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - users
      - movies
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.entrypoints=web"
      - "traefik.http.routers.front.rule=Host(`front.dev.neuvy.eu`)"
      - "traefik.http.routers.front.service=front"
      - "traefik.http.services.front.loadbalancer.server.port=3000"
  users:
    container_name: users
    build: ./backend
    depends_on:
      mysql:
        condition: service_healthy
    command: uvicorn users.main:app --reload --workers 1 --host 0.0.0.0 --port 80
    volumes:
      - ./backend/users:/usr/src/users
    expose:
      - 80
    ports:
      - 8004:80
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.users.entrypoints=web"
      - "traefik.http.routers.users.rule=Host(`users.dev.neuvy.eu`)"
      - "traefik.http.routers.users.service=users"
      - "traefik.http.services.users.loadbalancer.server.port=80"
  movies:
    container_name: movies
    build: ./backend
    depends_on:
      mysql:
        condition: service_healthy
    command: uvicorn movies.main:app --reload --workers 1 --host 0.0.0.0 --port 80
    volumes:
      - ./backend/movies:/usr/src/movies
    expose:
      - 80
    ports:
      - 8005:80
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.movies.entrypoints=web"
      - "traefik.http.routers.movies.rule=Host(`movies.dev.neuvy.eu`)"
      - "traefik.http.routers.movies.service=movies"
      - "traefik.http.services.movies.loadbalancer.server.port=80"

  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=moviequest
      - MYSQL_USER=fastapi
      - MYSQL_PASSWORD=fastapi
    volumes:
      - ./backend/db/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-ppass"]
      interval: 1s
      timeout: 3s
      retries: 20