version: '3.7'

services:
  front:
    container_name: front
    build: 
      context: ./frontend
      dockerfile: Dockerfile-dev
    command: npm run dev
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - users
      - movies
  users:
    container_name: users
    build: ./backend
    depends_on:
      - mysql
    command: uvicorn users.main:app --reload --workers 1 --host 0.0.0.0 --port 80
    volumes:
      - ./backend/users:/usr/src/users
    ports:
      - 8004:80
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
  movies:
    container_name: movies
    build: ./backend
    depends_on:
      - mysql
    command: uvicorn movies.main:app --reload --workers 1 --host 0.0.0.0 --port 80
    volumes:
      - ./backend/movies:/usr/src/movies
    ports:
      - 8005:80
    environment:
      - ENVIRONMENT=dev
      - TESTING=0

  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=moviequest
      - MYSQL_USER=fastapi
      - MYSQL_PASSWORD=fastapi
    volumes:
      - ./backend/db/mysql:/var/lib/mysql