http:
    middlewares:
        my-jwt-validation-middleware:
            plugin:
                jwt-validation-middleware:
                    secret: ThisIsMyVerySecret
                    optional: false
                    payloadHeaders:
                        X-Custom-Header1: sub
                        X-Custom-Header2: name
                    authQueryParam: authToken
                    authCookieName: authToken
                    forwardAuth: false