name: build-deploy-front
on:
  push:
    paths:
    - 'front/**'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Build and publish Docker Image to GitHub Container Registry
      # You may pin to the exact commit or the version.
      # uses: TCPShield/gp-docker-action@65486288374aeae8705fc543405dc4d23de6060b
      uses: TCPShield/gp-docker-action@1.1.13
      with:
        # Github username to push Docker image from
        github-username: estebanneuu
        # GitHub token to push Docker image to GitHub Container Registry
        github-token: ${{ secrets.TOKEN_GITHUB_ACTION }}
        # Docker Image tag
        image-tag: latest
        build-context: ./front
        

  #redeploy:
  #  name: Redeploy webhook call
  #  runs-on: ubuntu-18.04
  #  needs: [docker]
  #  steps:
  #    - name: Deploy docker container webhook
  #      uses: joelwmale/webhook-action@master
  #      env:
  #        WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
  #        data: "{ 'myField': 'myFieldValue'}"
